var R=R||{};R._namespaces={};R.global=this;R.namespace=function(a){if(R._namespaces[a])throw Error("Namespace '"+a+"' already defined!");R._namespaces[a]=1;a=a.split(".");for(var b=R,c;a.length&&(c=a.shift());)b=b[c]?b[c]:b[c]={}};R._unsupported=function(a,b){throw Error(a+" is unsupported in "+b.getClassName());};R.isUndefined=function(a){return typeof a==="undefined"};R.isEmpty=function(){return R.isUndefined(obj)||obj===null||typeof obj==="string"&&/\s*/g.test(obj)===""};R.namespace("debug");R.namespace("lang");
R.namespace("struct");R.namespace("math");R.namespace("engine");R.namespace("collision");R.namespace("components");R.namespace("objects");R.namespace("particles");R.namespace("physics");R.namespace("physics.collision");R.namespace("physics.collision.shapes");R.namespace("physics.common");R.namespace("physics.common.math");R.namespace("physics.dynamics");R.namespace("physics.dynamics.contacts");R.namespace("physics.dynamics.joints");R.namespace("rendercontexts");R.namespace("resources");R.namespace("resources.loaders");
R.namespace("resources.types");R.namespace("sound");R.namespace("spatial");R.namespace("storage");R.namespace("text");function now(){return new Date}
R.debug.ConsoleRef=Base.extend({constructor:function(){},dumpWindow:null,combiner:function(){for(var a="",b=0;b<arguments.length;b++)a+=arguments[b].toString();return a},cleanup:function(a){if(typeof a==="undefined")return"";else if(a===null)return"null";else if(typeof a=="function")return"function";else if(a.constructor==Array||a.slice&&a.join&&a.splice){var b="[";for(var c in a)b+=(b.length>1?",":"")+this.cleanup(a[c]);return b+"]"}else if(typeof a==="object"){b="{\n";for(c in a)b+=c+": "+this.cleanup(a[c])+
"\n";return b+"}\n"}else return a.toString()},fixArgs:function(a){for(var b=[],c=0;c<a.length;c++)a[c]?b.push(this.cleanup(a[c])):b.push("null");return b.join(" ")},debug:function(){},info:function(){},warn:function(){},error:function(){},trace:function(){},getClassName:function(){return"ConsoleRef"}});
R.debug.HTML=R.debug.ConsoleRef.extend({msgStore:null,firstTime:null,constructor:function(){this.msgStore=[];this.firstTime=true;$("head",document).append("<style> #debug-console { position: absolute; width: 400px; right: 10px; bottom: 5px; height: 98%; border: 1px solid; overflow: auto; font-family: 'Lucida Console',Courier; font-size: 8pt; color: black; } #debug-console .console-debug, #debug-console .console-info { background: white; } #debug-console .console-warn { font-style: italics; background: #00ffff; } #debug-console .console-error { color: red; background: yellow; font-weight: bold; } </style>");$(document).ready(function(){$(document.body).append($("<div id='debug-console'><!-- --\></div>"))});
window.onerror=function(a){a instanceof Error?this.error(a.message):this.error(a)}},clean:function(){$("#debug-console > span").length>150&&$("#debug-console > span:lt(150)").remove()},scroll:function(){var a=$("#debug-console")[0];if(a)$("#debug-console")[0].scrollTop=a.scrollHeight+1},store:function(a,b){if(this.firstTime)if(document.getElementById("debug-console")){this.firstTime=false;for(var c=0;c<this.msgStore.length;c++)switch(this.msgStore[c].t){case "i":this.info(this.msgStore[c].a);break;
case "d":this.debug(this.msgStore[c].a);break;case "w":this.warn(this.msgStore[c].a);break;case "e":this.error(this.msgStore[c].a);break}this.msgStore=null}else this.msgStore.push({t:a,a:this.fixArgs(b)})},fixArgs:function(a){return this.base(a).replace(/\n/g,"<br/>").replace(/ /g,"&nbsp;")},info:function(){this.clean();this.store("i",arguments);$("#debug-console").append($("<div class='console-info'>"+this.fixArgs(arguments)+"</div>"));this.scroll()},debug:function(){this.clean();this.store("d",
arguments);$("#debug-console").append($("<div class='console-debug'>"+this.fixArgs(arguments)+"</div>"));this.scroll()},warn:function(){this.clean();this.store("w",arguments);$("#debug-console").append($("<div class='console-warn'>"+this.fixArgs(arguments)+"</div>"));this.scroll()},error:function(){this.clean();this.store("e",arguments);$("#debug-console").append($("<div class='console-error'>"+this.fixArgs(arguments)+"</div>"));this.scroll()},getClassName:function(){return"R.debug.HTML"}});
R.debug.Safari=R.debug.ConsoleRef.extend({constructor:function(){},info:function(){console.log.apply(console,arguments)},debug:function(){console.debug.apply(console,arguments)},warn:function(){console.warn.apply(console,arguments)},error:function(){console.error.apply(console,arguments)},getClassName:function(){return"R.debug.Safari"}});
R.debug.Opera=R.debug.ConsoleRef.extend({constructor:function(){},info:function(){window.opera.postError(this.fixArgs(arguments))},debug:function(){window.opera.postError(["[D]",this.fixArgs(arguments)])},warn:function(){window.opera.postError(["[W]",this.fixArgs(arguments)])},error:function(){window.opera.postError(["[E!]",this.fixArgs(arguments)])},getClassName:function(){return"R.debug.Opera"}});
R.debug.Firebug=R.debug.ConsoleRef.extend({constructor:function(){},info:function(){typeof firebug!="undefined"?firebug.d.console.log.apply(firebug.d.console,arguments):console.info.apply(console,arguments)},debug:function(){typeof firebug!="undefined"?firebug.d.console.log.apply(firebug.d.console,arguments):console.debug.apply(console,arguments)},warn:function(){typeof firebug!="undefined"?firebug.d.console.log.apply(firebug.d.console,arguments):console.warn.apply(console,arguments)},error:function(){typeof firebug!=
"undefined"?firebug.d.console.log.apply(firebug.d.console,arguments):console.error.apply(console,arguments)},trace:function(){typeof console!="undefined"&&console.trace.apply(arguments)},getClassName:function(){return"R.debug.Firebug"}});
R.debug.MSIE=R.debug.ConsoleRef.extend({constructor:function(){},info:function(){console.log(this.fixArgs(arguments))},debug:function(){console.info(this.fixArgs(arguments))},warn:function(){console.warn(this.fixArgs(arguments))},error:function(){console.error(this.fixArgs(arguments))},getClassName:function(){return"R.debug.MSIE"}});
R.debug.Console=Base.extend({constructor:null,consoleRef:null,DEBUGLEVEL_ERRORS:4,DEBUGLEVEL_WARNINGS:3,DEBUGLEVEL_DEBUG:2,DEBUGLEVEL_INFO:1,DEBUGLEVEL_VERBOSE:0,DEBUGLEVEL_NONE:-1,verbosity:null,startup:function(){R.debug.Console.verbosity=R.debug.Console.DEBUGLEVEL_ERRORS;R.debug.Console.consoleRef=R.engine.Support.checkBooleanParam("debug")&&(R.engine.Support.checkBooleanParam("simWii")||jQuery.browser.Wii)?new R.debug.HTML:typeof firebug!="undefined"||typeof console!="undefined"&&console.firebug?
new R.debug.Firebug:typeof console!="undefined"&&jQuery.browser.msie?new R.debug.MSIE:jQuery.browser.chrome||jQuery.browser.safari?new R.debug.Safari:jQuery.browser.opera?new R.debug.Opera:new R.debug.ConsoleRef},setConsoleRef:function(a){if(a instanceof R.debug.ConsoleRef)R.debug.Console.consoleRef=a},setDebugLevel:function(a){R.debug.Console.verbosity=a},getDebugLevel:function(){return R.debug.Console.verbosity},checkVerbosity:function(a){return R.debug.Console.verbosity!=R.debug.Console.DEBUGLEVEL_NONE&&
R.debug.Console.verbosity==R.debug.Console.DEBUGLEVEL_VERBOSE||a!=R.debug.Console.DEBUGLEVEL_VERBOSE&&a>=R.debug.Console.verbosity},log:function(){R.Engine.debugMode&&R.debug.Console.checkVerbosity(R.debug.Console.DEBUGLEVEL_VERBOSE)&&R.debug.Console.consoleRef.debug.apply(R.debug.Console.consoleRef,arguments)},info:function(){R.Engine.debugMode&&R.debug.Console.checkVerbosity(R.debug.Console.DEBUGLEVEL_INFO)&&R.debug.Console.consoleRef.debug.apply(R.debug.Console.consoleRef,arguments)},debug:function(){R.Engine.debugMode&&
R.debug.Console.checkVerbosity(R.debug.Console.DEBUGLEVEL_DEBUG)&&R.debug.Console.consoleRef.info.apply(R.debug.Console.consoleRef,arguments)},warn:function(){R.Engine.debugMode&&R.debug.Console.checkVerbosity(R.debug.Console.DEBUGLEVEL_WARNINGS)&&R.debug.Console.consoleRef.warn.apply(R.debug.Console.consoleRef,arguments)},error:function(){R.debug.Console.checkVerbosity(R.debug.Console.DEBUGLEVEL_ERRORS)&&R.debug.Console.consoleRef.error.apply(R.debug.Console.consoleRef,arguments)},trace:function(){R.debug.Console.consoleRef.trace()}});
var Assert=function(a,b){var c=false;try{if(!a){c=true;R.debug.Console.setDebugLevel(R.debug.Console.DEBUGLEVEL_ERRORS);if(arguments.length>1)for(var d=1;d<arguments.length;d++){R.debug.Console.error("*ASSERT* ",arguments[d]);R.debug.Console.trace()}R.Engine.shutdown()}}catch(e){d=R.debug.Console.getDebugLevel();R.debug.Console.setDebugLevel(R.debug.Console.DEBUGLEVEL_WARNINGS);R.debug.Console.warn("*ASSERT* 'test' would result in an exception: ",e);R.debug.Console.setDebugLevel(d)}if(c)throw Error(b);
},AssertWarn=function(a,b){try{if(!a){R.debug.Console.setDebugLevel(R.debug.Console.DEBUGLEVEL_WARNINGS);if(arguments.length>1)for(var c=1;c<arguments.length;c++)R.debug.Console.warn("*ASSERT-WARN* ",arguments[c]);R.debug.Console.warn(b)}}catch(d){c=R.debug.Console.getDebugLevel();R.debug.Console.setDebugLevel(R.debug.Console.DEBUGLEVEL_WARNINGS);R.debug.Console.warn("*ASSERT-WARN* 'test' would result in an exception: ",d);R.debug.Console.setDebugLevel(c)}};
R.debug.Profiler={profileStack:[],allProfiles:{},profiles:[],running:false};R.debug.Profiler.start=function(){R.debug.Profiler.resetProfiles();R.debug.Profiler.running=true};R.debug.Profiler.stop=function(){R.debug.Profiler.dump();R.debug.Profiler.running=false};
R.debug.Profiler.enter=function(a){if(R.debug.Profiler.running){var b=R.debug.Profiler.allProfiles[a];if(b==null)b=R.debug.Profiler.allProfiles[a]={name:a,startMS:now(),execs:0,totalMS:0,instances:1,pushed:false};else{b.startMS=b.instances==0?now():b.startMS;b.instances++}R.debug.Profiler.profileStack.push(b)}};
R.debug.Profiler.exit=function(){if(R.debug.Profiler.running){if(R.debug.Profiler.profileStack.length==0){typeof console!=="undefined"&&console.error("Profile stack underflow");throw"Profile stack underflow";}var a=R.debug.Profiler.profileStack.pop();a.endMS=new Date;a.execs++;a.instances--;a.totalMS+=a.instances==0?a.endMS.getTime()-a.startMS.getTime():0;if(!a.pushed){a.pushed=true;R.debug.Profiler.profiles.push(a)}}};
R.debug.Profiler.resetProfiles=function(){R.debug.Profiler.profileStack=[];R.debug.Profiler.allProfiles={};R.debug.Profiler.profiles=[]};
R.debug.Profiler.dump=function(){if(R.debug.Profiler.running){if(R.debug.Profiler.profileStack.length>0){var a="";for(var b in R.debug.Profiler.profileStack)a+=(a.length>0?",":"")+b;R.debug.Console.error("Profile stack overflow.  Running profiles: ",a)}a=now();a=a.getHours()+":"+a.getMinutes()+":"+a.getSeconds();b=R.debug.Profiler.profiles.reverse();var c=0,d="";for(var e in b){var g=Math.round(b[e].totalMS/b[e].execs);c+=b[e].totalMS;d+="# "+b[e].name+" | "+(b[e].totalMS<1?"<1":b[e].totalMS)+" ms | "+
b[e].execs+" @ "+(g<1?"<1":g)+" ms\n"}d+="# Total Time: | "+c+" ms | \n";R.debug.Console.warn("PROFILER RESULTS @ "+a+"\n---------------------------------------------------\n");R.debug.Console.info(d);R.debug.Profiler.resetProfiles()}};
R.debug.Profiler.wireObjects=function(a){for(var b in a)for(var c in a[b].prototype)try{if(typeof a[b].prototype[c]=="function"&&a[b].prototype.hasOwnProperty(c)&&c!="constructor"){var d=function(){try{R.debug.Profiler.enter(arguments.callee.ob+"."+arguments.callee.o+"()");return arguments.callee.f.apply(this,arguments)}finally{R.debug.Profiler.exit()}};d.f=a[b].prototype[c];d.o=c;d.ob=a[b].getClassName();a[b].prototype[c]=d}}catch(e){}};
R.lang.Math2={state:1,m:4294967296,a:1103515245,c:12345,MAX_INT:4294967295,seed:function(a){R.lang.Math2.state=a?a:Math.floor(Math.random()*(R.lang.Math2.m-1))},randomInt:function(){R.lang.Math2.state=(R.lang.Math2.a*R.lang.Math2.state+R.lang.Math2.c)%R.lang.Math2.m;return R.lang.Math2.state},random:function(){return R.lang.Math2.randomInt()/(R.lang.Math2.m-1)},randomRange:function(a,b,c){a=a+R.lang.Math2.random()*b;return c?Math.floor(a):a},parseBin:function(a){if(!isNaN(a))return R.global.parseInt(a,
2)},toHex:function(a){if(!isNaN(a))return"0x"+a.toString(16)},toBinary:function(a){if(!isNaN(a))return a.toString(2)}};R.lang.Math2.seed();
R.engine.Support=Base.extend({constructor:null,indexOf:function(a,b,c){if(!a)return-1;if(Array.prototype.indexOf)return a.indexOf(b,c);else{var d=a.length;c=Number(c)||0;c=c<0?Math.ceil(c):Math.floor(c);if(c<0)c+=d;for(;c<d;c++)if(c in a&&a[c]===b)return c;return-1}},arrayRemove:function(a,b){if(a){var c=R.engine.Support.indexOf(a,b);c!=-1&&a.splice(c,1)}},isEmpty:function(a){return a==null||$.trim(a)===""},filter:function(a,b,c){if(!a)return null;if(Array.prototype.filter)return a.filter(b,c);else{var d=
a.length;if(typeof b!="function")throw new TypeError;for(var e=[],g=0;g<d;g++)if(g in a){var f=a[g];b.call(c,f,g,a)&&e.push(f)}return e}},forEach:function(a,b,c){if(a)if(Array.prototype.forEach)a.forEach(b,c);else{var d=a.length;if(typeof b!="function")throw new TypeError;for(var e=0;e<d;e++)e in a&&b.call(c,a[e],e,a)}},fillArray:function(a,b,c){for(var d=0;d<b;d++)a[d]=c},getPath:function(a){var b=a.lastIndexOf("/");return a.substr(0,b)},getQueryParams:function(){if(!R.engine.Support.parms){R.engine.Support.parms=
{};var a=window.location.toString().split("?")[1];if(a){a=a.split("&");for(var b=0;b<a.length;b++){var c=a[b].split("=");R.engine.Support.parms[c[0]]=c.length>1?c[1]:""}}}return R.engine.Support.parms},checkBooleanParam:function(a){return R.engine.Support.getQueryParams()[a]&&(R.engine.Support.getQueryParams()[a]=="true"||R.engine.Support.getQueryParams()[a]=="1"||R.engine.Support.getQueryParams()[a].toLowerCase()=="yes"||R.engine.Support.getQueryParams()[a].toLowerCase()=="y")},checkStringParam:function(a,
b){return R.engine.Support.getStringParam(a,null)==b},checkNumericParam:function(a,b){return R.engine.Support.getStringParam(a,null)==b},getNumericParam:function(a,b){return Number(R.engine.Support.getStringParam(a,b))},getStringParam:function(a,b){return R.engine.Support.getQueryParams()[a]||b},toJSON:function(a){return!typeof JSON=="undefined"?JSON.stringify(a):null},cleanSource:function(a,b){var c=a.replace(/((["'])[^;\n\r]*\2)|(\/\/.*$)/gm,"$1").replace(/\/\*(\n|.)*?\*\//gm,"").replace(/^[ \t]*(.*?)[ \t]*$/gm,
"$1").replace(/\s*\n$/gm,"");b||(c=c.replace(/(\n|\r)/gm,""));return c},parseJSON:function(a){a=R.engine.Support.cleanSource(a);if(typeof JSON!="undefined")try{return JSON.parse(a,function(c,d){var e;if(typeof d==="string")if(e=/^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2}(?:\.\d*)?)Z$/.exec(d))return new Date(Date.UTC(+e[1],+e[2]-1,+e[3],+e[4],+e[5],+e[6]));return d})}catch(b){R.debug.Console.warn("Cannot parse JSON: "+b.message);return null}else return R.engine.Support.evalJSON(a)},evalJSON:function(a){a=
R.engine.Support.cleanSource(a);try{return eval("("+a+")")}catch(b){R.debug.Console.warn("Cannot eval JSON: "+b.message);return null}},quoteString:function(a){return!typeof JSON=="undefined"?JSON.quote(a):null},checkOS:function(){navigator.userAgent.toLowerCase();return OS=/windows nt 6\.0/.test(userAgent)?"Windows Vista":/windows nt 6\.1/.test(userAgent)?"Windows 7":/windows nt 5\.1/.test(userAgent)?"Windows XP":/windows/.test(userAgent)?"Windows":/android 1\./.test(userAgent)?"Android 1.x":/android 2\./.test(userAgent)?
"Android 2.x":/android/.test(userAgent)?"Android":/x11/.test(userAgent)?"X11":/linux/.test(userAgent)?"Linux":/Mac OS X/.test(userAgent)?"Mac OS X":/macintosh/.test(userAgent)?"Macintosh":"unknown"},sysInfo:function(){if(!R.engine.Support._sysInfo){var a={emulated:false,defined:false,text:false,textMetrics:false,contexts:{ctx2D:false,ctxGL:false}};if(document.addEventListener){var b=document.createElement("canvas");if(typeof b!="undefined"&&typeof b.getContext=="function"){a.defined=true;var c=b.getContext("2d");
if(typeof c!="undefined"){a.contexts.ctx2D=true;a.text=typeof c.fillText=="function";a.textMetrics=typeof c.measureText=="function"}try{if(typeof b.getContext("glcanvas")!="undefined")a.contexts.ctxGL=true}catch(d){}}}if(typeof FlashCanvas!="undefined"){a.emulated=true;a.defined=true;a.contexts.ctx2D=true;a.text=true;a.textMetrics=true}R.engine.Support._sysInfo={browser:$.browser.chrome?"chrome":$.browser.android?"android":$.browser.Wii?"wii":$.browser.iPhone?"iphone":$.browser.safari?"safari":$.browser.firefox?
"firefox":$.browser.mozilla?"mozilla":$.browser.opera?"opera":$.browser.msie?"msie":"unknown",version:$.browser.version,agent:navigator.userAgent,platform:navigator.platform,cpu:navigator.cpuClass||navigator.oscpu,OS:R.engine.Support.checkOS(),language:navigator.language,online:navigator.onLine,cookies:navigator.cookieEnabled,fullscreen:window.fullScreen||false,support:{xhr:typeof XMLHttpRequest!=="undefined",threads:typeof Worker!=="undefined",sockets:typeof WebSocket!=="undefined",storage:typeof Storage!==
"undefined"?{local:typeof localStorage!=="undefined",session:typeof sessionStorage!=="undefined",database:typeof indexedDB!=="undefined"}:null,geo:typeof navigator.geolocation!=="undefined",canvas:a}};$(document).ready(function(){R.engine.Support._sysInfo=$.extend(R.engine.Support._sysInfo,{width:$(window).width(),height:$(window).height(),viewWidth:$(document).width(),viewHeight:$(document).height()})})}return R.engine.Support._sysInfo},whenReady:function(a,b){typeof a!="undefined"?b():setTimeout(arguments.callee,
50)}});
R.engine.Linker=Base.extend({constructor:null,classDefinitions:{},processed:{},resolvedClasses:{},resolvedFiles:{},loadClasses:[],queuedClasses:{},classLoaderTimer:null,classTimer:null,failTimer:null,waiting:{},define:function(a){if(typeof a["class"]==="undefined")throw new SyntaxError("Missing 'class' key in class definition!");var b=a["class"];if(R.engine.Linker.resolvedClasses[b]!=null)throw new ReferenceError("Class '"+b+"' is already defined!");R.debug.Console.debug("R.engine.Linker => Process definition for ",b);
R.engine.Linker.classDefinitions[b]=a;var c=[];if(a.requires&&a.requires.length>0)c=c.concat(a.requires);var d=[];if(a.includes&&a.includes.length>0)d=d.concat(a.includes);if(c.length==0&&d.length==0)R.engine.Linker._initClass(b);else{if(!R.engine.Linker.processed[b]){R.engine.Linker.processed[b]=true;R.engine.Linker.resolvedClasses[b]||(R.engine.Linker.queuedClasses[b]=true)}for(a=[];c.length>0;){b=c.shift();R.engine.Linker.resolvedClasses[b]||a.push(b)}for(c=[];d.length>0;){b=d.shift();R.engine.Linker.resolvedFiles[b]||
c.push(b)}for(;c.length>0;){b=c.shift();if(!R.engine.Linker.processed[b]){R.engine.Script.loadNow(b,function(e,g){if(g===R.engine.Script.SCRIPT_LOADED)R.engine.Linker.resolvedFiles[e]=true});R.engine.Linker.processed[b]=true}}for(;a.length>0;){b=a.shift();if(!R.engine.Linker.processed[b]){R.engine.Linker.processed[b]=true;R.engine.Linker.loadClasses.push(b)}}R.engine.Linker.loadClasses.length>0&&setTimeout(function(){R.engine.Linker.classLoader()},100);if(R.engine.Linker.classTimer==null){R.engine.Linker.failTimer=
setTimeout(function(){R.engine.Linker._failure()},1E4);R.engine.Linker.classTimer=setTimeout(function(){R.engine.Linker._processClasses()},100)}}},classLoader:function(){for(;R.engine.Linker.loadClasses.length>0;)R.engine.Linker._doLoad(R.engine.Linker.loadClasses.shift())},_doLoad:function(a){var b=a.split(".");b.shift();b[0]=="engine"&&b.shift();b="/"+b.join("/").toLowerCase()+".js";R.engine.Linker.waiting[b]=a;R.debug.Console.log("Loading "+b);R.engine.Script.loadNow(b,R.engine.Linker._loaded)},
_loaded:function(a,b){var c=R.engine.Linker.waiting[a];delete R.engine.Linker.waiting[a];if(b===R.engine.Script.SCRIPT_LOADED){R.debug.Console.log("R.engine.Linker => Initializing "+c);R.engine.Linker.queuedClasses[c]=true}else R.debug.Console.error("R.engine.Linker => "+c+" failed to load!")},_processClasses:function(){var a=0,b=0,c=[];for(var d in R.engine.Linker.queuedClasses){a++;var e=R.engine.Linker.classDefinitions[d];if(!e)throw Error("R.engine.Linker => Class '"+d+"' doesn't have a definition!");
var g=false;g=[];var f=[];if(e.requires&&e.requires.length>0)g=g.concat(e.requires);for(;g.length>0;){var h=g.shift();if(!R.engine.Linker.resolvedClasses[h]){var i=R.engine.Linker.classDefinitions[h];if(i&&i.requires)R.engine.Support.indexOf(i.requires,d)==-1&&f.push(h);else f.push(h)}}g=f.length>0;f=false;f=[];h=[];if(e.depends&&e.depends.length>0)f=f.concat(e.depends);for(;f.length>0;){i=f.shift();if(!R.engine.Linker.resolvedClasses[i]){var j=R.engine.Linker.classDefinitions[i];if(j&&j.requires)R.engine.Support.indexOf(j.requires,
d)==-1&&h.push(i);else if(j&&j.depends)R.engine.Support.indexOf(j.depends,d)==-1&&h.push(i);else h.push(i)}}f=h.length>0;if(!(g||f)){g=false;e=e.includes||[];for(f=0;f<e.length;f++)if(!R.engine.Linker.resolvedFiles[e[f]]){g=true;break}if(!g){R.engine.Linker._initClass(d);c.push(d);b++}}}for(;c.length>0;)delete R.engine.Linker.queuedClasses[c.shift()];if(b!=0){clearTimeout(R.engine.Linker.failTimer);R.engine.Linker.failTimer=setTimeout(function(){R.engine.Linker._failure()},1E4)}c=0;for(var k in R.engine.Linker.queuedClasses)c++;
if(c>0||a>b)R.engine.Linker.classTimer=setTimeout(function(){R.engine.Linker._processClasses()},100);else if(a==b){clearTimeout(R.engine.Linker.failTimer);R.engine.Linker.classTimer=null}},_initClass:function(a){for(var b=R.global,c=a.split(".");c.length>1;)b=b[c.shift()];c=c.shift();var d=b[c];b[c]=$.isFunction(d)?d():d;typeof b[c]!=="undefined"&&b[c].resolved&&b[c].resolved();R.debug.Console.log("R.engine.Linker => "+a+" initialized");R.engine.Linker.resolvedClasses[a]=true},_failure:function(){clearTimeout(R.engine.Linker.failTimer);
clearTimeout(R.engine.Linker.classTimer);clearTimeout(R.engine.Linker.classLoader);R.debug.Console.error("R.engine.Linker => FAILURE TO LOAD CLASSES!","Resolved: ",R.engine.Linker.resolvedClasses," Unprocessed: ",R.engine.Linker.queuedClasses," ClassDefs: ",R.engine.Linker.classDefinitions)}});
R.Engine=Base.extend({version:"v2.0.0.2",constructor:null,options:{},idRef:0,gameObjects:{},timerPool:{},livingObjects:0,fpsClock:33,frameTime:0,engineLocation:null,defaultContext:null,debugMode:false,localMode:false,started:false,running:false,shuttingDown:false,upTime:0,downTime:0,skipFrames:true,soundsEnabled:false,worldTime:0,liveTime:0,shutdownCallbacks:[],loadingCSS:"<style type='text/css'>div.loadbox {width:325px;height:30px;padding:10px;font:10px Arial;border:1px outset gray;-moz-border-radius:10px;-webkit-border-radius:10px} #engine-load-progress { position:relative;border:1px inset gray;width:300px;height:5px} #engine-load-progress .bar {background:silver;}</style>",
setOptions:function(a){var b;if(a.defaults)b=a.defaults;var c,d,e,g;if(a.platforms&&a.platforms[R.engine.Support.sysInfo().OS])if((c=a.platforms[R.engine.Support.sysInfo().OS])&&c.defaults)d=c.defaults;if(a.versions)for(var f in a.versions)if(parseFloat(R.engine.Support.sysInfo().version)>=parseFloat(f))e=a.versions[f];if(c&&c.versions)for(f in c.versions)if(parseFloat(R.engine.Support.sysInfo().version)>=parseFloat(f))g=c.versions[f];$.extend(R.Engine.options,b,d,e,g)},setDebugMode:function(a){R.Engine.debugMode=
a},getDebugMode:function(){return R.Engine.debugMode},isSoundEnabled:function(){return R.Engine.soundsEnabled},setFPS:function(a){Assert(a!=0,"You cannot have a framerate of zero!");R.Engine.fpsClock=Math.floor(1E3/a)},getFPS:function(){return Math.floor(1/R.Engine.fpsClock*1E3)},getActualFPS:function(){return Math.floor(1/R.Engine.frameTime*1E3)},getFrameTime:function(){return R.Engine.fpsClock},getDrawTime:function(){return R.Engine.frameTime},getEngineLoad:function(){return R.Engine.frameTime/
R.Engine.fpsClock},getDefaultContext:function(){if(R.Engine.defaultContext==null)R.Engine.defaultContext=R.rendercontexts.DocumentContext.create();return R.Engine.defaultContext},getEnginePath:function(){if(R.Engine.engineLocation==null)for(var a=document.getElementsByTagName("head")[0].getElementsByTagName("script"),b=0;b<a.length;b++){var c=a[b].src,d=c.match(/(.*\/engine)\/runtime\/engine\.js/);if(c!=null&&d){R.Engine.engineLocation=d[1];break}}return R.Engine.engineLocation},create:function(a){if(R.Engine.shuttingDown===
true){R.debug.Console.warn("Engine shutting down, '"+a+"' destroyed because it would create an orphaned reference");a.destroy()}else{Assert(R.Engine.started===true,"Creating an object when the engine is stopped!",a);R.Engine.idRef++;var b=a.getName()+R.Engine.idRef;R.debug.Console.log("CREATED Object ",b,"[",a,"]");R.Engine.livingObjects++;return b}},destroy:function(a){if(a==null)R.debug.Console.warn("NULL reference passed to Engine.destroy()!  Ignored.");else{var b=a.getId();R.debug.Console.log("DESTROYED Object ",
b,"[",a,"]");R.Engine.livingObjects--}},addTimer:function(a,b){R.Engine.timerPool[a]=b},removeTimer:function(a){R.Engine.timerPool[a]=null;delete R.Engine.timerPool[a]},getObject:function(){return null},loadEngineScripts:function(){R.engine.Script.loadStylesheet("/css/engine.css");R.engine.Linker._doLoad("R.engine.Game");R.engine.Linker._doLoad("R.engine.PooledObject");R.engine.Linker._doLoad("R.rendercontexts.AbstractRenderContext");R.engine.Linker._doLoad("R.rendercontexts.RenderContext2D");R.engine.Linker._doLoad("R.rendercontexts.HTMLElementContext");
R.engine.Linker._doLoad("R.rendercontexts.DocumentContext")},startup:function(a){Assert(R.Engine.running==false,"An attempt was made to restart the engine!");if(R.Engine.browserSupportCheck()){R.Engine.upTime=now().getTime();R.Engine.debugMode=a?true:false;R.Engine.started=true;R.Engine.loadEngineScripts()}},run:function(){if(!(R.Engine.shuttingDown||R.Engine.running)){for(var a in R.Engine.timerPool)R.Engine.timerPool[a].restart();a="[";a+=R.Engine.debugMode?"DEBUG":"";a+=R.Engine.localMode?a.length>
0?" LOCAL":"LOCAL":"";a+="]";R.debug.Console.warn(">>> Engine started. "+(a!="[]"?a:""));R.Engine.running=true;R.Engine.shuttingDown=false;R.debug.Console.debug(">>> sysinfo: ",R.engine.Support.sysInfo());R.Engine.globalTimer=window.setTimeout(function(){R.Engine.engineTimer()},this.fpsClock)}},pause:function(){if(!R.Engine.shuttingDown){R.debug.Console.debug("Pausing all timers");for(var a in R.Engine.timerPool)R.Engine.timerPool[a].pause();R.debug.Console.warn(">>> Engine paused <<<");window.clearTimeout(R.Engine.globalTimer);
R.Engine.running=false}},onShutdown:function(a){R.Engine.shuttingDown!==true&&R.Engine.shutdownCallbacks.push(a)},shutdown:function(){if(!R.Engine.shuttingDown){R.Engine.shuttingDown=true;if(!R.Engine.running&&R.Engine.started){R.Engine.running=true;setTimeout(function(){R.Engine.shutdown()},R.Engine.fpsClock*2)}else{R.Engine.started=false;window.clearTimeout(R.Engine.dependencyProcessor);R.debug.Console.warn(">>> Engine shutting down...");for(window.clearTimeout(R.Engine.globalTimer);R.Engine.shutdownCallbacks.length>
0;)R.Engine.shutdownCallbacks.shift()();if(R.Engine.metricDisplay){R.Engine.metricDisplay.remove();R.Engine.metricDisplay=null}R.debug.Console.debug("Cancelling all timers");for(var a in R.Engine.timerPool)R.Engine.timerPool[a].cancel();R.Engine.timerPool={};R.Engine.downTime=now().getTime();R.debug.Console.warn(">>> Engine stopped.  Runtime: "+(R.Engine.downTime-R.Engine.upTime)+"ms");R.Engine.running=false;R.Engine.getDefaultContext().destroy();if(typeof R.engine.PooledObject!="undefined")R.engine.PooledObject.objectPool=
null;AssertWarn(R.Engine.livingObjects==0,"Object references not cleaned up!");R.Engine.loadedScripts={};R.Engine.scriptLoadCount=0;R.Engine.scriptsProcessed=0;R.Engine.defaultContext=null;R.Engine.UNIT_TESTING||R.Engine.cleanup()}}},cleanup:function(){var a=$("#debug-console").remove();$(document.body).empty();a.length!=0&&$(document.body).append(a);$("head script",document).remove();R.engine.Linker.cleanup();R.Engine.shuttingDown=false},initObject:function(){throw new SyntaxError("Unsupported - See R.Engine.define() instead");
},define:function(a){R.engine.Linker.define(a)},browserSupportCheck:function(){if(R.engine.Support.checkBooleanParam("disableBrowserCheck"))return true;var a=R.engine.Support.sysInfo(),b="This browser is not currently supported by <i>The Render Engine</i>.<br/><br/>";b+="Please see <a href='http://www.renderengine.com' target='_blank'>the list of ";b+="supported browsers</a> for more information.";switch(a.browser){case "iPhone":case "android":case "msie":case "chrome":case "Wii":case "safari":case "mozilla":case "firefox":case "opera":return true;
case "unknown":$(document).ready(function(){R.Engine.shutdown();$("body",document).append($("<div class='unsupported'>").html(b))})}return false},toString:function(){return"The Render Engine "+R.Engine.version},engineTimer:function(){if(!R.Engine.shuttingDown){var a=R.Engine.fpsClock;if(R.Engine.running&&R.Engine.getDefaultContext()!=null){R.Engine.vObj=0;R.Engine.worldTime=now().getTime();R.Engine.getDefaultContext().update(null,R.Engine.worldTime);R.Engine.frameTime=now().getTime()-R.Engine.worldTime;
R.Engine.liveTime=R.Engine.worldTime-R.Engine.upTime;var b=a-R.Engine.frameTime;a=R.Engine.skipFrames?b>0?b:a:R.Engine.fpsClock;R.Engine.droppedFrames+=b<=0?Math.round(b*-1/R.Engine.fpsClock):0;R.Engine.doMetrics()}R.Engine.globalTimer=setTimeout(function(){R.Engine.engineTimer()},a)}},doMetrics:function(){R.debug&&R.debug.Metrics&&R.debug.Metrics.doMetrics()},include:function(a){R.engine.Script.include(a)},loadGame:function(a,b,c){R.engine.Script.loadGame(a,b,c)}},{globalTimer:null});
R.engine.Script=Base.extend({constructor:null,scriptQueue:[],loadedScripts:{},scriptLoadCount:0,scriptsProcessed:0,scriptRatio:0,queuePaused:false,pauseReps:0,callbacks:{},SCRIPT_NOT_FOUND:false,SCRIPT_LOADED:true,include:function(a){R.engine.Script.loadNow(a)},loadNow:function(a,b){R.engine.Script.doLoad(R.Engine.getEnginePath()+a,a,b)},loadScript:function(a){R.engine.Script.scriptQueue.push(a);R.engine.Script.runScriptQueue()},ajaxLoad:function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,true);
d.onreadystatechange=function(){d.readyState==4&&c(d,d.status)};a=null;if(b){a="";for(var e in b)a+=(a.length==0?"?":"&")+e+"="+encodeURIComponent(b[e])}d.send(a)},loadText:function(a,b,c){if(typeof b=="function"){c=b;b=null}R.engine.Script.ajaxLoad(a,b,function(d){c(d.responseText,d.status)})},loadJSON:function(a,b,c){if(typeof b=="function"){c=b;b=null}R.engine.Script.ajaxLoad(a,b,function(d){function e(j){return j.replace(/(".*".*|)(\/\/.*$)/gm,function(k,l){return l}).replace(/[\n\r\t]*/g,"")}
var g=null;try{var f=d.responseText;if(f){var h=e(f);g=R.engine.Support.parseJSON(h)}}catch(i){}c(g,d.status)})},runScriptQueue:function(){if(!R.engine.Script.scriptQueueTimer){R.engine.Script.scriptQueueTimer=setInterval(function(){if(R.engine.Script.queuePaused){if(R.engine.Script.pauseReps++>500){R.debug.Console.error("Script queue was paused for 5 seconds and not resumed -- restarting...");R.engine.Script.pauseReps=0;R.engine.Script.pauseQueue(false)}}else{R.engine.Script.pauseReps=0;if(R.engine.Script.scriptQueue.length>
0)R.engine.Script.processScriptQueue();else{clearInterval(R.engine.Script.scriptQueueTimer);R.engine.Script.scriptQueueTimer=null}}},10);R.engine.Script.readyForNextScript=true}},setQueueCallback:function(a){R.engine.Script.scriptQueue.push(a);R.engine.Script.runScriptQueue()},pauseQueue:function(a){R.engine.Script.queuePaused=a},processScriptQueue:function(){if(R.engine.Script.scriptQueue.length>0&&R.engine.Script.readyForNextScript){R.engine.Script.readyForNextScript=false;var a=R.engine.Script.scriptQueue.shift();
if(typeof a==="function"){a();R.engine.Script.readyForNextScript=true}else R.engine.Script.doLoad(a)}},doLoad:function(a,b,c){if(R.Engine.started){var d=a.replace(/[\/\.]/g,"_");if(R.engine.Script.loadedScripts[d]==null){R.engine.Script.loadedScripts[d]=a;R.engine.Script.scriptLoadCount++;R.engine.Script.updateProgress();if(c){R.debug.Console.log("Push callback for ",b);R.engine.Script.callbacks[b]=c}if($.browser.Wii)$.get(a,function(f){if(R.engine.Linker.parseSyntax(f)){var h=document.createElement("script");
h.type="text/javascript";$(h).text(f);document.getElementsByTagName("head")[0].appendChild(h);R.engine.Script.readyForNextScript=true;R.engine.Script.scriptLoadCount--;R.engine.Script.updateProgress();R.debug.Console.debug("Loaded '"+a+"'")}},"text");else{d=document.createElement("script");d.src=a;d.type="text/javascript";var e=function(){if(!this.readyState||this.readyState=="loaded"||this.readyState=="complete"){var f=arguments.callee.node,h=arguments.callee.fullPath,i=R.engine.Script.callbacks[arguments.callee.simpPath];
R.debug.Console.debug("Loaded '"+h+"'");R.engine.Script.handleScriptDone();if($.isFunction(i)){R.debug.Console.debug("Callback for '"+h+"'");i(b,R.engine.Script.SCRIPT_LOADED);delete R.engine.Script.callbacks[arguments.callee.simpPath]}R.Engine.localMode||$(f).remove()}R.engine.Script.readyForNextScript=true};e.node=d;e.fullPath=a;e.simpPath=b;var g=function(){var f=arguments.callee.cb;R.debug.Console.error("File not found: ",a);f&&f(b,R.engine.Script.SCRIPT_NOT_FOUND);R.engine.Script.readyForNextScript=
true};g.cb=c;if($.browser.msie){d.defer=true;d.onreadystatechange=e}else d.onload=e;d.onerror=g;document.getElementsByTagName("head")[0].appendChild(d)}}else R.engine.Script.readyForNextScript=true}},loadGame:function(a,b,c){var d=c||b;$(document).ready(function(){if($("span.loading").length==0){$("head").append($(R.Engine.loadingCSS));var e="<span id='loading' class='intrinsic'><table border='0' style='width:100%;height:100%;'><tr>";e+="<td style='width:100%;height:100%;' valign='middle' align='center'><div class='loadbox'>Loading ";
e+=d+"...<div id='engine-load-progress'></div><span id='engine-load-info'></span></div>";e+="</td></tr></table></span>";$("body",document).append($(e))}});R.engine.Script.loadEngineOptions();R.engine.Script.gameLoadTimer=setInterval(function(){if(R.engine.Script.optionsLoaded&&R.rendercontexts.DocumentContext&&R.rendercontexts.DocumentContext.started){R.Engine.run();clearInterval(R.engine.Script.gameLoadTimer);R.engine.Script.gameLoadTimer=null;R.debug.Console.debug("Loading '"+a+"'");R.engine.Script.loadScript(a);
if(b)R.engine.Script.gameRunTimer=setInterval(function(){if(typeof window[b]!="undefined"&&window[b].setup){clearInterval(R.engine.Script.gameRunTimer);R.debug.Console.warn("Starting: "+b);$("#loading.intrinsic").remove();window[b].setup()}},100)}},2)},loadEngineOptions:function(){R.engine.Script.optionsLoaded=false;R.engine.Script.loadJSON(R.Engine.getEnginePath()+"/configs/"+R.engine.Support.sysInfo().browser+".config",function(a,b){if(b==200){R.debug.Console.debug("Engine options loaded for: "+
R.engine.Support.sysInfo().browser);R.Engine.setOptions(a)}else R.debug.Console.log("Engine options for: "+R.engine.Support.sysInfo().browser+" responded with "+b);R.engine.Script.optionsLoaded=true})},load:function(a){R.engine.Script.loadScript(R.Engine.getEnginePath()+a)},handleScriptDone:function(){R.engine.Script.scriptsProcessed++;R.engine.Script.scriptRatio=R.engine.Script.scriptsProcessed/R.engine.Script.scriptLoadCount;R.engine.Script.scriptRatio=R.engine.Script.scriptRatio>1?1:R.engine.Script.scriptRatio;
R.engine.Script.updateProgress()},updateProgress:function(){var a=jQuery("#engine-load-progress");if(a.length>0){if(a.css("position")!="relative"||a.css("position")!="absolute")a.css("position","relative");var b=a.width();b=Math.floor(b*R.engine.Script.scriptRatio);var c=jQuery("#engine-load-progress .bar");if(c.length==0){c=jQuery("<div class='bar' style='position: absolute; top: 0px; left: 0px; height: 100%;'></div>");a.append(c)}c.width(b);jQuery("#engine-load-info").text(R.engine.Script.scriptsProcessed+
" of "+R.engine.Script.scriptLoadCount)}},loadStylesheet:function(a,b,c){a=(b?"":R.Engine.getEnginePath())+a;R.engine.Script.setQueueCallback(function(){c?$("head",document).append($("<link type='text/css' rel='stylesheet' href='"+a+"'/>")):$.get(a,function(d){d=d.replace(/(\$<enginePath>)/g,R.Engine.getEnginePath());R.engine.Support.sysInfo().browser=="msie"?$("head",document).append($("<style type='text/css'>"+d+"</style>")):$("head",document).append($("<style type='text/css'/>").text(d));R.debug.Console.debug("Stylesheet loaded '"+
a+"'")},"text")})},dumpScripts:function(){for(var a in this.loadedScripts)R.debug.Console.debug(R.engine.Script.loadedScripts[a])},clearScriptCache:function(){R.engine.Script.loadedScripts={}}});
R.debug.Metrics=Base.extend({constructor:null,metrics:{},metricDisplay:null,profileDisplay:null,metricSampleRate:10,lastMetricSample:10,showMetricsWindow:false,showMetricsProfile:false,vObj:0,droppedFrames:0,profilePos:0,profiles:{},toggleMetrics:function(){R.debug.Metrics.showMetricsWindow=!R.debug.Metrics.showMetricsWindow},showMetrics:function(){R.debug.Metrics.showMetricsWindow=true},showProfile:function(){R.debug.Metrics.showMetricsProfile=true},hideMetrics:function(){R.debug.Metrics.showMetricsWindow=
false},manMetrics:function(){if($("div.metric-button.minimize").length>0){$("div.metric-button.minimize").removeClass("minimize").addClass("maximize").attr("title","maximize");$("div.metrics").css("height",17);$("div.metrics .items").hide()}else{$("div.metric-button.maximize").removeClass("maximize").addClass("minimize").attr("title","minimize");$("div.metrics .items").show();$("div.metrics").css("height","auto")}},metricButton:function(a,b){return $("<div class='metric-button "+a+"' title='"+a+"'><!-- --\></div>").click(b)},
render:function(){if(R.debug.Metrics.showMetricsWindow&&!R.debug.Metrics.metricDisplay){R.debug.Metrics.metricDisplay=$("<div/>").addClass("metrics");R.debug.Metrics.metricDisplay.append(R.debug.Metrics.metricButton("run",function(){R.Engine.run()}));R.debug.Metrics.metricDisplay.append(R.debug.Metrics.metricButton("pause",function(){R.Engine.pause()}));R.debug.Metrics.metricDisplay.append(R.debug.Metrics.metricButton("shutdown",function(){R.Engine.shutdown()}));R.debug.Metrics.metricDisplay.append(R.debug.Metrics.metricButton("close",
function(){R.debug.Metrics.hideMetrics()}));R.debug.Metrics.metricDisplay.append(R.debug.Metrics.metricButton("minimize",function(){R.debug.Metrics.manMetrics()}));R.debug.Metrics.metricDisplay.append($("<div class='items'/>"));R.debug.Metrics.metricDisplay.appendTo($("body"))}if((this.showMetricsWindow||this.showMetricsProfile)&&this.lastMetricSample--==0){R.debug.Metrics.add("FPS",R.Engine.getFPS(),false,"#");R.debug.Metrics.add("aFPS",R.Engine.getActualFPS(),true,"#");R.debug.Metrics.add("availTime",
R.Engine.fpsClock,false,"#ms");R.debug.Metrics.add("frameGenTime",R.Engine.frameTime,true,"#ms");R.debug.Metrics.add("engineLoad",Math.floor(R.Engine.getEngineLoad()*100),true,"#%");R.debug.Metrics.add("visibleObj",R.Engine.vObj,false,"#");R.debug.Metrics.add("droppedFrames",R.Engine.droppedFrames,false,"#");R.debug.Metrics.add("upTime",Math.floor((R.Engine.worldTime-R.Engine.upTime)/1E3),false,"# sec");R.debug.Metrics.update();R.debug.Metrics.lastMetricSample=R.debug.Metrics.metricSampleRate}if(R.debug.Metrics.showMetricsProfile&&
R.engine.Support.sysInfo().browser=="msie"&&parseFloat(R.engine.Support.sysInfo().version)<9)R.debug.Metrics.showMetricsProfile=false;if(R.debug.Metrics.showMetricsProfile&&!R.debug.Metrics.profileDisplay){R.debug.Metrics.profileDisplay=$("<canvas width='150' height='100'/>").addClass("engine-profile");R.debug.Metrics.profileDisplay.appendTo($("body"));R.debug.Metrics.profileDisplay[0].getContext("2d").save()}},setSampleRate:function(a){R.debug.Metrics.lastMetricSample=1;R.debug.Metrics.metricSampleRate=
a},add:function(a,b,c,d){if(c){c=R.debug.Metrics.metrics[a]?R.debug.Metrics.metrics[a].values:[];if(c.length==0){c.push(b);c.push(b);c.push(b)}c.shift();c.push(b);b=Math.floor((c[0]+c[1]+c[2])*0.33);R.debug.Metrics.metrics[a]={val:d?d.replace("#",b):b,values:c,act:b}}else R.debug.Metrics.metrics[a]={val:d?d.replace("#",b):b,act:b}},remove:function(a){R.debug.Metrics.metrics[a]=null;delete R.debug.Metrics.metrics[a]},update:function(){var a="",b;if(R.debug.Metrics.showMetricsProfile){b=R.debug.Metrics.profileDisplay[0].getContext("2d");
b.save();b.translate(147,0)}for(var c in R.debug.Metrics.metrics){if(R.debug.Metrics.showMetricsWindow)a+=c+": "+R.debug.Metrics.metrics[c].val+"<br/>";if(R.debug.Metrics.showMetricsProfile)switch(c){case "engineLoad":this.drawProfilePoint("#ffff00",R.debug.Metrics.metrics[c].act);break;case "visibleObj":this.drawProfilePoint("#339933",R.debug.Metrics.metrics[c].act);break;case "poolLoad":this.drawProfilePoint("#a0a0ff",R.debug.Metrics.metrics[c].act);break}}R.debug.Metrics.showMetricsWindow&&$(".items",
R.debug.Metrics.metricDisplay).html(a);if(R.debug.Metrics.showMetricsProfile){b.restore();R.debug.Metrics.moveProfiler()}},drawProfilePoint:function(a,b){var c=R.debug.Metrics.profileDisplay[0].getContext("2d");c.strokeStyle=a;try{if(!isNaN(b)){c.beginPath();c.moveTo(0,R.debug.Metrics.profiles[a]||100);c.lineTo(1,100-b<1?1:100-b);c.closePath();c.stroke();R.debug.Metrics.profiles[a]=100-b<1?1:100-b}}catch(d){}},moveProfiler:function(){var a=R.debug.Metrics.profileDisplay[0].getContext("2d"),b=a.getImageData(1,
0,149,100);a.save();a.translate(-1,0);a.putImageData(b,0,0);a.restore()},doMetrics:function(){if(R.debug.Metrics.showMetricsWindow||R.debug.Metrics.showMetricsProfile)R.debug.Metrics.render();else if(!R.debug.Metrics.showMetricsWindow&&R.debug.Metrics.metricDisplay){R.debug.Metrics.metricDisplay.remove();R.debug.Metrics.metricDisplay=null}}});R.engine.Support.checkBooleanParam("metrics")&&R.debug.Metrics.showMetrics();R.engine.Support.checkBooleanParam("profile")&&R.debug.Metrics.showProfile();R.debug.Console.startup();
R.Engine.defaultOptions={skipFrames:true,billboards:true,textUseBillboards:true,hardwareAccel:false,pointAsArc:true,transientMathObject:false,useDirtyRectangles:false};R.Engine.options=$.extend({},R.Engine.defaultOptions);R.Engine.startup();R.Engine.setDebugMode(R.engine.Support.checkBooleanParam("debug"));R.Engine.getDebugMode()&&R.debug.Console.setDebugLevel(R.engine.Support.getNumericParam("debugLevel",R.debug.Console.DEBUGLEVEL_DEBUG));R.Engine.localMode=R.engine.Support.checkBooleanParam("local");
